name:                Moogle-Engine
version:             0.1.0.0
github:              "githubuser/Moogle-Engine"
license:             BSD-3-Clause
author:              "Front Story"
maintainer:          "example@example.com"
copyright:           "2024 Front Story"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Moogle-Engine#readme>

dependencies:
  - base >= 4.7 && < 5
  - directory 
  - text 
  - parsec 
  - http-types 
  - filepath
  - happstack-server
  - open-browser
  - containers
  - aeson
  - scotty
  - wai-middleware-static
  - multipart
  - bytestring
  - wai
  - wai-extra
  - parallel
  - containers
  - array
  - hxt
  - zip-archive
  - xml
  - text

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  Moogle-Engine:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Moogle-Engine

tests:
  Moogle-Engine-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Moogle-Engine
